/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "青飞",
  "description": "青飞的笔记",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "author",
        "content": "青飞"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress 介绍, vuepress 说明, 青飞"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "assets/img/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Vuepress",
      "frontmatter": {
        "home": true,
        "title": "Vuepress",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3a49649c",
      "path": "/"
    },
    {
      "title": "关于我2",
      "frontmatter": {
        "navbar": false,
        "title": "关于我2"
      },
      "regularPath": "/about2.html",
      "relativePath": "about2.md",
      "key": "v-3c23834b",
      "path": "/about2.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        }
      ]
    },
    {
      "title": "csso",
      "frontmatter": {
        "title": "csso"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-582b9d37",
      "path": "/css/"
    },
    {
      "title": "CssB",
      "frontmatter": {
        "title": "CssB"
      },
      "regularPath": "/css/ccc.html",
      "relativePath": "css/ccc.md",
      "key": "v-c8971d88",
      "path": "/css/ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "你好1",
          "slug": "你好1"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-3"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-4"
        },
        {
          "level": 2,
          "title": "你好3",
          "slug": "你好3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-2"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-5"
        }
      ]
    },
    {
      "title": "About",
      "frontmatter": {
        "navbar": false,
        "title": "About"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-ea6fddee",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        }
      ]
    },
    {
      "title": "CssB",
      "frontmatter": {
        "title": "CssB"
      },
      "regularPath": "/css/bbb.html",
      "relativePath": "css/bbb.md",
      "key": "v-1a520e9c",
      "path": "/css/bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "你好1",
          "slug": "你好1"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-3"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-4"
        },
        {
          "level": 2,
          "title": "你好3",
          "slug": "你好3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-2"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-5"
        }
      ]
    },
    {
      "title": "CssA",
      "frontmatter": {
        "title": "CssA"
      },
      "regularPath": "/css/aaa.html",
      "relativePath": "css/aaa.md",
      "key": "v-ce20a808",
      "path": "/css/aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "你好1",
          "slug": "你好1"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-3"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-4"
        },
        {
          "level": 2,
          "title": "你好3",
          "slug": "你好3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-2"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-5"
        }
      ]
    },
    {
      "title": "JavaScript o",
      "frontmatter": {
        "title": "JavaScript o"
      },
      "regularPath": "/js/",
      "relativePath": "js/README.md",
      "key": "v-1e3adf75",
      "path": "/js/"
    },
    {
      "title": "JSA",
      "frontmatter": {
        "title": "JSA"
      },
      "regularPath": "/js/aa.html",
      "relativePath": "js/aa.md",
      "key": "v-7ecf81d4",
      "path": "/js/aa.html",
      "headers": [
        {
          "level": 2,
          "title": "你好1",
          "slug": "你好1"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-3"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-4"
        },
        {
          "level": 2,
          "title": "你好3",
          "slug": "你好3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-2"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-5"
        }
      ]
    },
    {
      "title": "JSC",
      "frontmatter": {
        "title": "JSC"
      },
      "regularPath": "/js/cc.html",
      "relativePath": "js/cc.md",
      "key": "v-b6ae11d4",
      "path": "/js/cc.html",
      "headers": [
        {
          "level": 2,
          "title": "你好1",
          "slug": "你好1"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-3"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-4"
        },
        {
          "level": 2,
          "title": "你好3",
          "slug": "你好3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-2"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-5"
        }
      ]
    },
    {
      "title": "JSB",
      "frontmatter": {
        "title": "JSB"
      },
      "regularPath": "/js/bb.html",
      "relativePath": "js/bb.md",
      "key": "v-32a09b16",
      "path": "/js/bb.html",
      "headers": [
        {
          "level": 2,
          "title": "你好1",
          "slug": "你好1"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-2"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-3"
        },
        {
          "level": 3,
          "title": "你好2",
          "slug": "你好2-4"
        },
        {
          "level": 2,
          "title": "你好3",
          "slug": "你好3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-2"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-3"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-4"
        },
        {
          "level": 3,
          "title": "你好4",
          "slug": "你好4-5"
        }
      ]
    }
  ],
  "themeConfig": {
    "lastUpdated": "更行时间",
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about/"
      },
      {
        "text": "Languages",
        "items": [
          {
            "text": "Group1",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Guide",
                "link": "/about/"
              }
            ]
          },
          {
            "text": "Group2",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Guide",
                "link": "/about/"
              }
            ]
          }
        ]
      },
      {
        "text": "External",
        "link": "https://baidu.com"
      }
    ],
    "sidebar": {
      "/css/": [
        "aaa",
        "bbb",
        "ccc"
      ],
      "/js/": [
        "aa",
        "bb",
        "cc"
      ],
      "/": [
        "",
        "about",
        "about2"
      ]
    }
  }
}